name: CI/CD Pipeline

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t hln_scrapper:${{ github.sha }} .

    - name: Run unittests
      run: docker run hln_scrapper:${{ github.sha }} python -m pytest .

    - name: Push Docker image
      if: ${{ success() }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker tag hln_scrapper:${{ github.sha }} DOCKERHUB_USERNAME/hln_scrapper:${{ github.sha }}
          docker push DOCKERHUB_USERNAME/hln_scrapper:${{ github.sha }} run hln_scrapper pytest