name: CI/CD Pipeline
on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: github checkout
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t hln_scrapper:${{ github.sha }} .

    - name: Run unittests
      run: docker run hln_scrapper:${{ github.sha }} python -m pytest .

    - name: Log in to Docker Hub
      if: ${{ success() }}
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag hln_scrapper:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/hln_scrapper:${{ github.sha }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/hln_scrapper:${{ github.sha }} 